services:
    chernoff_datatable.templating:
        class: 'Chernoff\DatatableBundle\Templating\Templating'
        arguments:
            - '@Twig\Environment'
            - '%chernoff_datatable.templates%'

    chernoff_datatable:
        class: 'Chernoff\Datatable\Manager'
        public: true
        arguments:
            - '@chernoff_datatable.templating'

    chernoff_datatables.twig.extension:
        class: Chernoff\DatatableBundle\Twig\DatatableTwigExtension
        tags:
            - { name: twig.extension }
